### ISSUE TITLE
Refactor project to Typescript

### ISSUE THREAD

**Issue by greenlucid** [kleros/governor-snapshot#10]
# no big export default

```js
export default ({
  hey: "hello"
  hello: "hello",
  test: 10
})
```

to

```tsx

interface Thing {
  hello: string
  hey: string
  test: number
}

const thing: Thing = {hello: "hello", hey: "hello", test: 10}

export default thing
```

why: autocomplete for imports is easier. more tidy and easy to refactor. better documented.

# refactor react components to typescript

change file extension to `.tsx`

use `React.FC` type for components

(this below is a personal preference, but i think it's desirable to avoid duplication) don't decompose props in the arguments of the component.

instead of:

```tsx
const Animals: React.FC<{dog: string, cat: string, mouse: string}> = ({dog, cat, mouse}) => {
  return (
    <div>
      i hate my dog {dog}, my cat {cat} and my mouse {mouse}
    </div>
  )
}
```

do
```tsx
const Animals: React.FC<{dog: string, cat: string, mouse: string}> = (p) => {
  return (
    <div>
      i hate my dog {p.dog}, my cat {p.cat} and my mouse {p.mouse}
    </div>
  )
}
```

you get autocomplete with the props, and then you don't need to pass duplicate stuff.

**Comment by herniadlf** [comment]
@greenlucid i've made several advances with this one. I think that i'm missing one or two files that are still in JS, but i want to share w/ you to check if its in the proper direction
