### ISSUE TITLE
Add Fork DAO governor (+ ability to connect to other chains)

### ISSUE THREAD

**Issue by greenlucid** [kleros/governor-snapshot#5]
Fork DAO deployed their governor here: https://blockscout.com/xdai/mainnet/address/0xf7dE5537eCD69a94695fcF4BCdBDeE6329b63322/read-contract#address-tabs
this is gnosis chain, with chainId 100.

As far as I've seen this frontend only works in Ethereum Mainnet, so it should be able to prompt the user to change chains when they click onto the newly added Fork DAO item.

**Comment by herniadlf** [comment]
I'll separate this in two steps (pull requests).

1) [Add the chain as a project attribute.](https://github.com/kleros/governor-snapshot/pull/9) 
2) [Add the specific forkdao governor support on gnosis chain](https://github.com/kleros/governor-snapshot/pull/8)

**Comment by greenlucid** [comment]
closed by #8, #9
